### ISSUE TITLE
Ruby 2.0 incompatibility

### ISSUE THREAD

**Issue by kke** [packethost/packet-rb#10]
`/Library/Ruby/Gems/2.0.0/gems/packethost-0.0.7/lib/packet/entity/serialization.rb:20:in `to_hash': undefined method `to_h' for #<Array:0x007fdc7b1d6528> (NoMethodError)`

`Array#to_h` is Ruby 2.1+ only.

**Comment by betawaffle** [comment]
Fixed by #11.
